name: Testing

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  tests:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    runs-on: ubuntu-latest

    strategy:

      fail-fast: false

      matrix:
        include:
          - php: "8.2"
            laravel: "9.*"

          - php: "8.2"
            laravel: "10.*"

          - php: "8.2"
            laravel: "11.*"

          - php: "8.2"
            laravel: "12.*"

          - php: "8.3"
            laravel: "13.*"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_sqlite
          coverage: none

      - name: Set Laravel version
        run: composer require "laravel/framework:${{ matrix.laravel }}" --no-update

      - name: Install dependencies
        run: composer config --global audit.block-insecure false && composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test
